const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const pt=(name,lat,lon,note='')=>({name,lat,lon,note});
const route=[pt('Bucharest',44.4268,26.1025,'Start / finish'),pt('Rânca',45.2911,23.6886,'Night 1'),pt('Urdele Pass',45.3457,23.6649,'Transalpina'),pt('Sibiu',45.7983,24.1256,'Night 2'),pt('Transapuseana',46.318,23.235,'Day 3'),pt('Alba Iulia',46.067,23.57,'Night 3'),pt('Sighișoara',46.2197,24.7926,'Day 4'),pt('Brașov',45.6579,25.6012,'Night 4'),pt('Bran Castle',45.515,25.3672,'Day 5'),pt('Cârțișoara',45.7251,24.5798,'Night 5'),pt('Bâlea Lake',45.6046,24.6173,'Day 6'),pt('Vidraru Dam',45.367,24.6308,'Day 6'),pt('Bucharest',44.4268,26.1025,'Finish')];
const wxCities=[['Rânca',45.2911,23.6886,'2026-08-01'],['Sibiu',45.7983,24.1256,'2026-08-02'],['Alba Iulia',46.067,23.57,'2026-08-03'],['Brașov',45.6579,25.6012,'2026-08-04'],['Cârțișoara',45.7251,24.5798,'2026-08-05'],['Bâlea Lake',45.6046,24.6173,'2026-08-06']];
const wikiTitles={'Bucharest':'Bucharest','Rânca':'Ranca, Gorj','Horezu Monastery':'Horezu Monastery','Polovragi Monastery':'Polovragi Monastery','Muierilor Cave':'Peștera Muierilor','Transalpina':'Transalpina (Romania)','Urdele Pass':'Transalpina (Romania)','Oașa Lake':'Oașa Lake','Câlnic Citadel':'Câlnic Citadel','Sibiu':'Sibiu','Transapuseana':'Transapuseana','Rimetea':'Rimetea','Alba Carolina Citadel':'Alba Iulia','Alba Iulia':'Alba Iulia','Sighișoara':'Sighișoara','Rupea Fortress':'Rupea Fortress','Viscri Fortified Church':'Viscri fortified church','Brașov':'Brașov','Bran Castle':'Bran Castle','Făgăraș Fortress':'Făgăraș Citadel','Cârța Abbey':'Cârța Monastery','Cârțișoara':'Cârțișoara','Transfăgărășan':'Transfăgărășan','Bâlea Waterfall':'Bâlea Waterfall','Bâlea Lake':'Bâlea Lake','Vidraru Dam':'Vidraru Dam','Curtea de Argeș Monastery':'Curtea de Argeș Cathedral'};
const imgCache={};
async function realImage(name){const title=wikiTitles[name]||name;if(imgCache[title])return imgCache[title];try{const r=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`,{cache:'no-store'});const j=await r.json();const src=j.originalimage?.source||j.thumbnail?.source||'';imgCache[title]=src;return src}catch{return''}}
const days=[
{d:1,r:'Bucharest → Rânca',km:'300–380 km',t:'6–7h',imgKey:'Rânca',city:'Rânca',start:pt('Bucharest',44.4268,26.1025),end:pt('Rânca',45.2911,23.6886),e:'Long opening ride into the Parâng Mountains.',st:[pt('Horezu Monastery',45.1686,24.0065,'UNESCO monastery, close to the westbound route'),pt('Polovragi Monastery',45.1824,23.8008,'Short scenic stop before Novaci'),pt('Muierilor Cave',45.1847,23.7516,'Optional only if the group is ahead of schedule')],food:[['Restaurant TARA','Romanian and European; strongest Tripadvisor option in Rânca'],['Restaurant Alessia','Convenient alternative with parking']],note:'Stop every 90–120 minutes and avoid arriving after dark.'},
{d:2,r:'Rânca → Transalpina → Sibiu',km:'230–260 km',t:'5–6h',imgKey:'Transalpina',city:'Sibiu',start:pt('Rânca',45.2911,23.6886),end:pt('Sibiu',45.7983,24.1256),e:'High-altitude curves, exposed ridges and fast-changing weather.',st:[pt('Urdele Pass',45.3457,23.6649,'Highest and most dramatic Transalpina section'),pt('Oașa Lake',45.5833,23.6197,'Natural rest point after the alpine section'),pt('Câlnic Citadel',45.8873,23.6573,'Small UNESCO detour before Sibiu')],food:[['Crama Sibiul Vechi','Traditional Romanian; very popular'],['Kombinat','Contemporary European'],['Casa Grinda','Highly rated central option']],note:'Fuel before climbing; expect fog, livestock and gravel near shoulders.'},
{d:3,r:'Sibiu → Transapuseana → Alba Iulia',km:'220–250 km',t:'5–6h',imgKey:'Transapuseana',city:'Alba Iulia',start:pt('Sibiu',45.7983,24.1256),end:pt('Alba Iulia',46.067,23.57),e:'Quieter ridge roads, villages and rolling Transylvanian scenery.',st:[pt('Transapuseana',46.318,23.235,'Main riding attraction; use only safe pull-offs'),pt('Rimetea',46.4535,23.5682,'Picturesque village beneath Piatra Secuiului'),pt('Alba Carolina Citadel',46.0687,23.5707,'Best evening walk after check-in')],food:[['Pub 13','Inside the citadel; strong reviews and atmosphere'],['Dante Cafe & Dine','Reliable broad menu'],['UNIO Vini','Premium dinner inside the fortress']],note:'Watch for animals, local traffic and possible roadworks.'},
{d:4,r:'Alba Iulia → Sighișoara → Brașov',km:'250–280 km',t:'6–7h',imgKey:'Sighișoara',city:'Brașov',start:pt('Alba Iulia',46.067,23.57),end:pt('Brașov',45.6579,25.6012),e:'The strongest culture day of the trip.',st:[pt('Sighișoara',46.2197,24.7926,'Allow about two hours for the citadel'),pt('Rupea Fortress',46.0397,25.2224,'Directly beside the E60 corridor'),pt('Viscri Fortified Church',46.0558,25.0931,'Optional modest detour; skip if timing slips')],food:[['Ograda','One of Brașov’s highest-rated options'],['La Ceaun – Piața Sfatului','Traditional Romanian in the old town'],['La Ceaun Weiss','Popular soups, stews and Romanian dishes']],note:'Historic-centre cobblestones can be slippery.'},
{d:5,r:'Brașov → Bran Castle → Cârțișoara',km:'190–220 km',t:'4–5h',imgKey:'Bran Castle',city:'Cârțișoara',start:pt('Brașov',45.6579,25.6012),end:pt('Cârțișoara',45.7251,24.5798),e:'Shorter sightseeing day through castle country.',st:[pt('Bran Castle',45.515,25.3672,'Arrive near opening time'),pt('Făgăraș Fortress',45.8416,24.9731,'Directly on the practical route east of Sibiu'),pt('Cârța Abbey',45.7841,24.5686,'Very short detour before Cârțișoara')],food:[['Hanul Patrisiei restaurant','Most convenient at the hotel; reviews are mixed, so keep expectations practical'],['Casa Bunicii Cârțișoara','Local Romanian alternative'],['Roadhouse Restaurant, Făgăraș area','Good fallback before reaching the hotel']],note:'Keep the day relaxed and sleep early.'},
{d:6,r:'Cârțișoara → Transfăgărășan → Bucharest',km:'300–330 km',t:'6–8h',imgKey:'Transfăgărășan',city:'Bâlea Lake',start:pt('Cârțișoara',45.7251,24.5798),end:pt('Bucharest',44.4268,26.1025),e:'Epic alpine finale with Bâlea Lake and Vidraru Dam.',st:[pt('Bâlea Waterfall',45.6375,24.6083,'Optional short stop before the climb'),pt('Bâlea Lake',45.6046,24.6173,'Main alpine highlight'),pt('Vidraru Dam',45.367,24.6308,'Directly on the southern descent'),pt('Curtea de Argeș Monastery',45.1636,24.6745,'Optional if daylight remains')],food:[['Carry snacks and water','Do not rely on fast service at the mountain stops'],['Curtea de Argeș','Use Google Maps nearby search for a late lunch if timing allows']],note:'Watch for stopped cars, fog and bears. Never stop near wildlife.'}
];
const checks=['Thermal layer and rain shell','Helmet, gloves, boots and armour','BMW R 1250 GS controls and riding modes checked','Tyres, fluids, lights and luggage straps','Offline Google Maps downloaded','Phone mount, charging cable and power bank','Romanian lei, documents, water and snacks'];
const wmo=c=>({0:['☀️','Clear'],1:['🌤️','Mostly clear'],2:['⛅','Partly cloudy'],3:['☁️','Overcast'],45:['🌫️','Fog'],61:['🌦️','Light rain'],63:['🌧️','Rain'],65:['🌧️','Heavy rain'],80:['🌦️','Showers'],81:['🌧️','Showers'],82:['⛈️','Heavy showers'],95:['⛈️','Thunderstorm']}[c]||['🌦️','Variable']);
const weather={};let map,liveMarker,accuracyCircle,watchId=null;
const coord=p=>`${p.lat},${p.lon}`;
function googleDirections(day,fromLive=false){const q=new URLSearchParams({api:'1',destination:coord(day.end),travelmode:'driving'});if(!fromLive)q.set('origin',coord(day.start));if(day.st.length)q.set('waypoints',day.st.slice(0,3).map(coord).join('|'));return`https://www.google.com/maps/dir/?${q}`}
function googleSearch(name){return`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name+', Romania')}`}
async function loadWeather(){$('#weatherGrid').innerHTML='<div class="weather">Loading live route weather…</div>';await Promise.all(wxCities.map(async c=>{try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${c[1]}&longitude=${c[2]}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Europe%2FBucharest&forecast_days=16`;let j=await(await fetch(u,{cache:'no-store'})).json(),i=j.daily.time.indexOf(c[3]),q=wmo(j.current.weather_code);weather[c[0]]={icon:q[0],desc:q[1],now:Math.round(j.current.temperature_2m),feel:Math.round(j.current.apparent_temperature),wind:Math.round(j.current.wind_speed_10m),trip:i>=0?`${Math.round(j.daily.temperature_2m_min[i])}–${Math.round(j.daily.temperature_2m_max[i])}°, rain ${j.daily.precipitation_probability_max[i]}%`:null}}catch{weather[c[0]]={err:true}}}));renderWeather();renderDays();$('#weatherStatus').textContent='Updated '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' · refreshes whenever the app opens.'}
function renderWeather(){$('#weatherGrid').innerHTML=wxCities.map(c=>{let w=weather[c[0]];return`<article class="weather"><div class="city">${c[0]}</div>${w&&!w.err?`<div class="temp">${w.icon} ${w.now}°</div><div class="cond">${w.desc} · feels ${w.feel}° · wind ${w.wind} km/h</div><div class="meta">${w.trip?'Trip day: '+w.trip:'Trip forecast appears automatically when available'}</div>`:'<div class="cond">Weather unavailable</div>'}</article>`}).join('')}
function wx(city){let w=weather[city];return w&&!w.err?`${w.icon} ${w.now}° now · feels ${w.feel}° · wind ${w.wind} km/h${w.trip?' · trip '+w.trip:''}`:'Live weather loading…'}
function nav(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+id)}
async function renderDays(){$('#days').innerHTML=days.map(x=>`<article class="day"><button class="dayOpen" data-day="${x.d}"><div class="dayArt" id="dayimg${x.d}"><span class="dayNo">0${x.d}</span></div><div class="dayCopy"><h3>${x.r}</h3><p>${x.e}</p><div class="metaRow"><span>🏍 ${x.km}</span><span>◷ ${x.t}</span></div><div class="status">${wx(x.city)}</div></div></button><div class="routeActions"><a class="mapBtn" target="_blank" rel="noopener" href="${googleDirections(x)}">Open full day in Google Maps</a><a class="mapBtn secondary" target="_blank" rel="noopener" href="${googleDirections(x,true)}">Navigate from my location</a></div></article>`).join('');for(const x of days){const src=await realImage(x.imgKey);if(src)$(`#dayimg${x.d}`).style.backgroundImage=`url('${src}')`}$$('[data-day]').forEach(b=>b.onclick=()=>showDay(+b.dataset.day))}
async function showDay(n){let x=days.find(v=>v.d===n),hero=await realImage(x.imgKey),stops='';for(const s of x.st){const src=await realImage(s.name);stops+=`<article class="stop">${src?`<img src="${src}" alt="${s.name}" loading="lazy">`:''}<div class="stopBody"><b>${s.name}</b><p>${s.note}</p><a class="textLink" target="_blank" rel="noopener" href="${googleSearch(s.name)}">Open point in Google Maps</a></div></article>`}const restaurants=x.food.map(r=>`<article class="restaurant"><div><b>${r[0]}</b><p>${r[1]}</p></div><a class="mapBtn secondary" target="_blank" rel="noopener" href="${googleSearch(r[0])}">Google Maps</a></article>`).join('');$('#detailContent').innerHTML=`<div class="detailHero" style="background-image:url('${hero}')"><div class="detailHeroCopy"><div class="ey" style="color:#dceee6">Day ${x.d}</div><h2>${x.r}</h2><p>${x.km} · ${x.t}</p></div></div><div class="routeActions detailActions"><a class="mapBtn" target="_blank" href="${googleDirections(x)}">Full route + stops</a><a class="mapBtn secondary" target="_blank" href="${googleDirections(x,true)}">Start from live location</a></div><div class="note"><b>Live weather</b><p>${wx(x.city)}</p></div><div class="section"><div class="ey">Recommended near-route stops</div><h3>Worth stopping for</h3>${stops}</div><div class="section"><div class="ey">Dinner near the hotel</div><h3>Restaurant options</h3>${restaurants}</div><div class="note warn"><b>🏍 BMW R 1250 GS rider note</b><p>${x.note}</p></div>`;nav('detail')}
function renderChecks(){$('#checks').innerHTML=checks.map((x,i)=>`<label class="check"><input type="checkbox" data-c="${i}"><span><b>${x}</b></span></label>`).join('');let s=JSON.parse(localStorage.getItem('motoChecks')||'[]');$$('[data-c]').forEach(c=>{c.checked=s.includes(+c.dataset.c);c.onchange=()=>localStorage.setItem('motoChecks',JSON.stringify($$('[data-c]').filter(x=>x.checked).map(x=>+x.dataset.c)))})}
function makeMap(){map=L.map('map',{scrollWheelZoom:false}).setView([45.7,24.5],7);const ll=[];L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);route.forEach(p=>{ll.push([p.lat,p.lon]);L.marker([p.lat,p.lon]).addTo(map).bindPopup(`<b>${p.name}</b><br>${p.note}<br><a target="_blank" href="${googleSearch(p.name)}">Google Maps</a>`)});L.polyline(ll,{color:'#103f35',weight:5,dashArray:'9 8'}).addTo(map);map.fitBounds(ll,{padding:[25,25]});const box=document.createElement('div');box.className='trackingPanel';box.innerHTML='<button id="trackLocation" class="mapBtn">Start live location</button><button id="stopLocation" class="mapBtn secondary" disabled>Stop tracking</button><div id="trackingStatus" class="status">Location tracking is off.</div>';document.querySelector('.routeWrap').appendChild(box);$('#trackLocation').onclick=startTracking;$('#stopLocation').onclick=stopTracking}
function startTracking(){if(!navigator.geolocation){$('#trackingStatus').textContent='Location is not supported on this device.';return}if(watchId!==null)return;$('#trackingStatus').textContent='Requesting location permission…';watchId=navigator.geolocation.watchPosition(pos=>{const {latitude,longitude,accuracy}=pos.coords;if(!liveMarker){liveMarker=L.marker([latitude,longitude]).addTo(map).bindPopup('Your live location');accuracyCircle=L.circle([latitude,longitude],{radius:accuracy,color:'#2b6c5b',fillOpacity:.12}).addTo(map)}else{liveMarker.setLatLng([latitude,longitude]);accuracyCircle.setLatLng([latitude,longitude]).setRadius(accuracy)}map.panTo([latitude,longitude]);$('#trackingStatus').textContent=`Live location active · accuracy about ${Math.round(accuracy)} m`;$('#trackLocation').disabled=true;$('#stopLocation').disabled=false},err=>{$('#trackingStatus').textContent='Location unavailable: '+err.message;stopTracking()},{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
function stopTracking(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null}$('#trackLocation').disabled=false;$('#stopLocation').disabled=true;$('#trackingStatus').textContent='Location tracking is off.'}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#back').onclick=()=>nav('itinerary');$('#share').onclick=async()=>{let d={title:'Romania Moto Loop',text:'Our BMW R 1250 GS Romania trip',url:location.href};navigator.share?await navigator.share(d).catch(()=>{}):(await navigator.clipboard.writeText(location.href),alert('Link copied'))};$('#refresh').onclick=loadWeather;renderDays();renderChecks();makeMap();loadWeather();realImage('Transfăgărășan').then(src=>{if(src)document.querySelector('.hero').style.backgroundImage=`linear-gradient(180deg,rgba(0,0,0,.03),rgba(6,42,35,.88)),url('${src}')`});let h=location.hash.slice(1);if(['overview','itinerary','essentials'].includes(h))nav(h);