const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const route=[['Bucharest',44.4268,26.1025,'Start / finish'],['Rânca',45.2911,23.6886,'Night 1'],['Urdele Pass',45.3457,23.6649,'Transalpina'],['Sibiu',45.7983,24.1256,'Night 2'],['Transapuseana',46.318,23.235,'Day 3'],['Alba Iulia',46.067,23.57,'Night 3'],['Sighișoara',46.2197,24.7926,'Day 4'],['Brașov',45.6579,25.6012,'Night 4'],['Bran Castle',45.515,25.3672,'Day 5'],['Cârțișoara',45.7251,24.5798,'Night 5'],['Bâlea Lake',45.6046,24.6173,'Day 6'],['Vidraru Dam',45.367,24.6308,'Day 6'],['Bucharest',44.4268,26.1025,'Finish']];
const wxCities=[['Rânca',45.2911,23.6886,'2026-08-01'],['Sibiu',45.7983,24.1256,'2026-08-02'],['Alba Iulia',46.067,23.57,'2026-08-03'],['Brașov',45.6579,25.6012,'2026-08-04'],['Cârțișoara',45.7251,24.5798,'2026-08-05'],['Bâlea Lake',45.6046,24.6173,'2026-08-06']];
const wikiTitles={'Bucharest':'Bucharest','Rânca':'Ranca, Gorj','Transalpina':'Transalpina (Romania)','Urdele Pass':'Transalpina (Romania)','Oașa Lake':'Oașa Lake','Sibiu':'Sibiu','Transapuseana':'Transapuseana','Rimetea':'Rimetea','Alba Carolina Citadel':'Alba Iulia','Alba Iulia':'Alba Iulia','Sighișoara':'Sighișoara','Rupea Fortress':'Rupea Fortress','Brașov':'Brașov','Bran Castle':'Bran Castle','Piatra Craiului views':'Piatra Craiului Mountains','Cârțișoara':'Cârțișoara','Transfăgărășan':'Transfăgărășan','Bâlea Waterfall':'Bâlea Waterfall','Bâlea Lake':'Bâlea Lake','Vidraru Dam':'Vidraru Dam','Curtea de Argeș':'Curtea de Argeș Cathedral'};
const imgCache={};
async function realImage(name){const title=wikiTitles[name]||name;if(imgCache[title])return imgCache[title];try{const r=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`,{cache:'no-store'});const j=await r.json();const src=j.originalimage?.source||j.thumbnail?.source||'';imgCache[title]=src;return src}catch(e){return''}}
const days=[
{d:1,r:'Bucharest → Rânca',km:'300–380 km',t:'6–7h',imgKey:'Rânca',city:'Rânca',e:'Long opening ride into the Parâng Mountains.',st:[['Bucharest','Departure point — leave early to beat city traffic'],['Rânca','Golden-hour mountain views if arrival timing allows']],food:'Restaurant TARA or Alessia.',note:'Stop every 90–120 minutes and avoid arriving after dark.'},
{d:2,r:'Rânca → Transalpina → Sibiu',km:'230–260 km',t:'5–6h',imgKey:'Transalpina',city:'Sibiu',e:'High-altitude curves, exposed ridges and fast-changing weather.',st:[['Urdele Pass','Highest and most dramatic Transalpina section'],['Oașa Lake','Calmer scenic stop after the pass'],['Sibiu','Piața Mare and Bridge of Lies']],food:'Kombinat in Sibiu.',note:'Fuel before climbing; expect fog, livestock and gravel near shoulders.'},
{d:3,r:'Sibiu → Transapuseana → Alba Iulia',km:'220–250 km',t:'5–6h',imgKey:'Transapuseana',city:'Alba Iulia',e:'Quieter ridge roads, villages and rolling Transylvanian scenery.',st:[['Transapuseana','Use only wide, safe pull-offs'],['Rimetea','Optional village detour'],['Alba Carolina Citadel','Best explored in the evening']],food:'PUB13 inside the citadel.',note:'Watch for animals, local traffic and possible roadworks.'},
{d:4,r:'Alba Iulia → Sighișoara → Brașov',km:'250–280 km',t:'6–7h',imgKey:'Sighișoara',city:'Brașov',e:'The strongest culture day of the trip.',st:[['Sighișoara','Allow 2–3 hours'],['Rupea Fortress','Optional elevated stop'],['Brașov','Council Square, Black Church and Tâmpa']],food:'Le Petit Bistro in Brașov.',note:'Historic-centre cobblestones can be slippery.'},
{d:5,r:'Brașov → Bran Castle → Cârțișoara',km:'190–220 km',t:'4–5h',imgKey:'Bran Castle',city:'Cârțișoara',e:'Shorter sightseeing day through castle country.',st:[['Bran Castle','Arrive near opening time'],['Piatra Craiului views','Strong mountain backdrops'],['Cârțișoara','Quiet base for the final pass']],food:'Curly-Burly near Cârțișoara.',note:'Keep the day relaxed and sleep early.'},
{d:6,r:'Cârțișoara → Transfăgărășan → Bucharest',km:'300–330 km',t:'6–8h',imgKey:'Transfăgărășan',city:'Bâlea Lake',e:'Epic alpine finale with Bâlea Lake and Vidraru Dam.',st:[['Bâlea Waterfall','Optional short stop before the climb'],['Bâlea Lake','Main alpine highlight'],['Vidraru Dam','Excellent southern-side viewpoint'],['Curtea de Argeș','Optional if daylight remains']],food:'Eat early and carry water and snacks.',note:'Watch for stopped cars, fog and bears. Never stop near wildlife.'}];
const places=[['View','Transalpina','Urdele Pass','The highest and most exposed section.','Transalpina'],['City','Sibiu','Historic centre','Piața Mare, Small Square and Bridge of Lies.','Sibiu'],['City','Alba Iulia','Alba Carolina Citadel','Large star-shaped fortress.','Alba Carolina Citadel'],['City','Sighișoara','Medieval Citadel','Clock Tower and cobbled lanes.','Sighișoara'],['City','Brașov','Old town & Tâmpa','Council Square and city viewpoint.','Brașov'],['Sight','Bran','Bran Castle','Go early to avoid August crowds.','Bran Castle'],['View','Transfăgărășan','Bâlea Lake','The defining alpine stop.','Bâlea Lake'],['View','Transfăgărășan','Vidraru Dam','Strong stop on the southern descent.','Vidraru Dam']];
const food=[['Rânca','TARA / Alessia','Mountain comfort food.'],['Sibiu','Kombinat','Modern dinner option.'],['Alba Iulia','PUB13','Dining inside the citadel.'],['Brașov','Le Petit Bistro','Old-town meal stop.'],['Cârțișoara','Curly-Burly','Relaxed gastropub.']];
const checks=['Thermal layer and rain shell','Helmet, gloves, boots and armour','BMW R 1250 GS controls and riding modes checked','Tyres, fluids, lights and luggage straps','Offline maps and hotel addresses','Phone mount, charging cable and power bank','Romanian lei, documents, water and snacks'];
const wmo=c=>({0:['☀️','Clear'],1:['🌤️','Mostly clear'],2:['⛅','Partly cloudy'],3:['☁️','Overcast'],45:['🌫️','Fog'],61:['🌦️','Light rain'],63:['🌧️','Rain'],65:['🌧️','Heavy rain'],80:['🌦️','Showers'],81:['🌧️','Showers'],82:['⛈️','Heavy showers'],95:['⛈️','Thunderstorm']}[c]||['🌦️','Variable']);
const weather={};
async function loadWeather(){$('#weatherGrid').innerHTML='<div class="weather">Loading live route weather…</div>';await Promise.all(wxCities.map(async c=>{try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${c[1]}&longitude=${c[2]}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Europe%2FBucharest&forecast_days=16`;let j=await (await fetch(u,{cache:'no-store'})).json(),i=j.daily.time.indexOf(c[3]),q=wmo(j.current.weather_code);weather[c[0]]={icon:q[0],desc:q[1],now:Math.round(j.current.temperature_2m),feel:Math.round(j.current.apparent_temperature),wind:Math.round(j.current.wind_speed_10m),trip:i>=0?`${Math.round(j.daily.temperature_2m_min[i])}–${Math.round(j.daily.temperature_2m_max[i])}°, rain ${j.daily.precipitation_probability_max[i]}%`:null}}catch(e){weather[c[0]]={err:true}}}));renderWeather();renderDays();$('#weatherStatus').textContent='Updated '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' · refreshes whenever the app opens.'}
function renderWeather(){$('#weatherGrid').innerHTML=wxCities.map(c=>{let w=weather[c[0]];return `<article class="weather"><div class="city">${c[0]}</div>${w&&!w.err?`<div class="temp">${w.icon} ${w.now}°</div><div class="cond">${w.desc} · feels ${w.feel}° · wind ${w.wind} km/h</div><div class="meta">${w.trip?'Trip day: '+w.trip:'Trip forecast appears automatically when available'}</div>`:'<div class="cond">Weather unavailable</div>'}</article>`}).join('')}
function wx(city){let w=weather[city];return w&&!w.err?`${w.icon} ${w.now}° now · feels ${w.feel}° · wind ${w.wind} km/h${w.trip?' · trip '+w.trip:''}`:'Live weather loading…'}
function nav(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+id)}
async function renderDays(){$('#days').innerHTML=days.map(x=>`<button class="day" data-day="${x.d}"><div class="dayArt" id="dayimg${x.d}"><span class="dayNo">0${x.d}</span></div><div class="dayCopy"><h3>${x.r}</h3><p>${x.e}</p><div class="metaRow"><span>🏍 ${x.km}</span><span>◷ ${x.t}</span></div><div class="status">${wx(x.city)}</div></div></button>`).join('');for(const x of days){const src=await realImage(x.imgKey);if(src)$(`#dayimg${x.d}`).style.backgroundImage=`url('${src}')`}$$('[data-day]').forEach(b=>b.onclick=()=>showDay(+b.dataset.day))}
async function showDay(n){let x=days.find(v=>v.d===n),hero=await realImage(x.imgKey),stops='';for(const s of x.st){const src=await realImage(s[0]);stops+=`<article class="stop">${src?`<img src="${src}" alt="${s[0]}" loading="lazy">`:''}<div class="stopBody"><b>${s[0]}</b><p>${s[1]}</p></div></article>`}$('#detailContent').innerHTML=`<div class="detailHero" style="background-image:url('${hero}')"><div class="detailHeroCopy"><div class="ey" style="color:#dceee6">Day ${x.d}</div><h2>${x.r}</h2><p>${x.km} · ${x.t}</p></div></div><div class="note"><b>Live weather</b><p>${wx(x.city)}</p></div><div class="section"><div class="ey">What to expect</div><h3>${x.e}</h3></div><div class="section"><div class="ey">Stops & photo points</div>${stops}</div><div class="note"><b>🍽 Food</b><p>${x.food}</p><p class="status">No restaurant photo is shown unless it can be verified as the actual place.</p></div><div class="note warn"><b>🏍 BMW R 1250 GS rider note</b><p>${x.note}</p></div>`;nav('detail')}
async function renderPlaces(f='All'){$('#filters').innerHTML=['All','View','City','Sight','Food'].map(x=>`<button class="filter ${x===f?'active':''}" data-filter="${x}">${x}</button>`).join('');let out='';if(f!=='Food'){for(const p of places.filter(p=>f==='All'||p[0]===f)){const src=await realImage(p[4]);out+=`<article class="place">${src?`<img src="${src}" alt="${p[2]}" loading="lazy">`:''}<div class="placeBody"><span class="tag">${p[0]}</span><h3>${p[2]}</h3><p><b>${p[1]}</b> · ${p[3]}</p></div></article>`}}if(f==='All'||f==='Food')food.forEach(p=>out+=`<article class="place"><div class="placeBody"><span class="tag">Food</span><h3>${p[1]}</h3><p><b>${p[0]}</b> · ${p[2]}</p><p class="status">Text only — no unverified restaurant image.</p></div></article>`);$('#placesList').innerHTML=out;$$('[data-filter]').forEach(b=>b.onclick=()=>renderPlaces(b.dataset.filter))}
function renderChecks(){$('#checks').innerHTML=checks.map((x,i)=>`<label class="check"><input type="checkbox" data-c="${i}"><span><b>${x}</b></span></label>`).join('');let s=JSON.parse(localStorage.getItem('motoChecks')||'[]');$$('[data-c]').forEach(c=>{c.checked=s.includes(+c.dataset.c);c.onchange=()=>localStorage.setItem('motoChecks',JSON.stringify($$('[data-c]').filter(x=>x.checked).map(x=>+x.dataset.c)))})}
function makeMap(){let m=L.map('map',{scrollWheelZoom:false}).setView([45.7,24.5],7),ll=[];L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(m);route.forEach(p=>{ll.push([p[1],p[2]]);L.marker([p[1],p[2]]).addTo(m).bindPopup(`<b>${p[0]}</b><br>${p[3]}<br><a target="_blank" href="https://www.openstreetmap.org/?mlat=${p[1]}&mlon=${p[2]}#map=14/${p[1]}/${p[2]}">Open location</a>`)});L.polyline(ll,{color:'#103f35',weight:5,dashArray:'9 8'}).addTo(m);m.fitBounds(ll,{padding:[25,25]})}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#back').onclick=()=>nav('itinerary');$('#share').onclick=async()=>{let d={title:'Romania Moto Loop',text:'Our BMW R 1250 GS Romania trip',url:location.href};navigator.share?await navigator.share(d).catch(()=>{}):(await navigator.clipboard.writeText(location.href),alert('Link copied'))};$('#refresh').onclick=loadWeather;renderDays();renderPlaces();renderChecks();makeMap();loadWeather();realImage('Transfăgărășan').then(src=>{if(src)document.querySelector('.hero').style.backgroundImage=`linear-gradient(180deg,transparent,rgba(6,42,35,.88)),url('${src}')`});let h=location.hash.slice(1);if(['overview','itinerary','places','essentials'].includes(h))nav(h);