const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const route=[['Bucharest',44.4268,26.1025,'Start / finish'],['Rânca',45.2911,23.6886,'Night 1'],['Urdele Pass',45.3457,23.6649,'Transalpina'],['Sibiu',45.7983,24.1256,'Night 2'],['Transapuseana',46.318,23.235,'Day 3'],['Alba Iulia',46.067,23.57,'Night 3'],['Sighișoara',46.2197,24.7926,'Day 4'],['Brașov',45.6579,25.6012,'Night 4'],['Bran Castle',45.515,25.3672,'Day 5'],['Cârțișoara',45.7251,24.5798,'Night 5'],['Bâlea Lake',45.6046,24.6173,'Day 6'],['Vidraru Dam',45.367,24.6308,'Day 6'],['Bucharest',44.4268,26.1025,'Finish']];
const wxCities=[['Rânca',45.2911,23.6886,'2026-08-01'],['Sibiu',45.7983,24.1256,'2026-08-02'],['Alba Iulia',46.067,23.57,'2026-08-03'],['Brașov',45.6579,25.6012,'2026-08-04'],['Cârțișoara',45.7251,24.5798,'2026-08-05'],['Bâlea Lake',45.6046,24.6173,'2026-08-06']];
const imgs={ranca:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85',transalpina:'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=85',sibiu:'https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=1200&q=85',alba:'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=85',sighisoara:'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=85',brasov:'https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=85',bran:'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=85',balea:'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?auto=format&fit=crop&w=1200&q=85',bike:'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=85'};
const days=[
{d:1,r:'Bucharest → Rânca',km:'300–380 km',t:'6–7h',img:imgs.ranca,city:'Rânca',e:'Long opening ride into the Parâng Mountains.',st:[['Horezu area','Coffee and fuel break',imgs.ranca],['Rânca viewpoints','Golden-hour mountain views',imgs.transalpina]],food:'Restaurant TARA or Alessia.',note:'Stop every 90–120 minutes and avoid arriving after dark.'},
{d:2,r:'Rânca → Transalpina → Sibiu',km:'230–260 km',t:'5–6h',img:imgs.transalpina,city:'Sibiu',e:'High-altitude curves, exposed ridges and fast-changing weather.',st:[['Urdele Pass','Highest and most dramatic Transalpina section',imgs.transalpina],['Oașa Lake','Calmer scenic stop after the pass',imgs.balea],['Sibiu old town','Piața Mare and Bridge of Lies',imgs.sibiu]],food:'Kombinat in Sibiu.',note:'Fuel before climbing; expect fog, livestock and gravel near shoulders.'},
{d:3,r:'Sibiu → Transapuseana → Alba Iulia',km:'220–250 km',t:'5–6h',img:imgs.alba,city:'Alba Iulia',e:'Quieter ridge roads, villages and rolling Transylvanian scenery.',st:[['Transapuseana viewpoints','Use only wide, safe pull-offs',imgs.transalpina],['Rimetea','Optional village detour',imgs.sibiu],['Alba Carolina Citadel','Best explored in the evening',imgs.alba]],food:'PUB13 inside the citadel.',note:'Watch for animals, local traffic and possible roadworks.'},
{d:4,r:'Alba Iulia → Sighișoara → Brașov',km:'250–280 km',t:'6–7h',img:imgs.sighisoara,city:'Brașov',e:'The strongest culture day of the trip.',st:[['Sighișoara Citadel','Allow 2–3 hours',imgs.sighisoara],['Rupea Fortress','Optional elevated stop',imgs.bran],['Brașov old town','Council Square, Black Church and Tâmpa',imgs.brasov]],food:'Le Petit Bistro in Brașov.',note:'Historic-centre cobblestones can be slippery.'},
{d:5,r:'Brașov → Bran Castle → Cârțișoara',km:'190–220 km',t:'4–5h',img:imgs.bran,city:'Cârțișoara',e:'Shorter sightseeing day through castle country.',st:[['Bran Castle','Arrive near opening time',imgs.bran],['Piatra Craiului views','Strong mountain backdrops',imgs.transalpina],['Cârțișoara','Quiet base for the final pass',imgs.ranca]],food:'Curly-Burly near Cârțișoara.',note:'Keep the day relaxed and sleep early.'},
{d:6,r:'Cârțișoara → Transfăgărășan → Bucharest',km:'300–330 km',t:'6–8h',img:imgs.balea,city:'Bâlea Lake',e:'Epic alpine finale with Bâlea Lake and Vidraru Dam.',st:[['Bâlea Waterfall','Optional short stop before the climb',imgs.balea],['Bâlea Lake','Main alpine highlight',imgs.balea],['Vidraru Dam','Excellent southern-side viewpoint',imgs.transalpina],['Curtea de Argeș','Optional if daylight remains',imgs.alba]],food:'Eat early and carry water and snacks.',note:'Watch for stopped cars, fog and bears. Never stop near wildlife.'}];
const places=[['View','Transalpina','Urdele Pass','The highest and most exposed section.',imgs.transalpina],['City','Sibiu','Historic centre','Piața Mare, Small Square and Bridge of Lies.',imgs.sibiu],['City','Alba Iulia','Alba Carolina Citadel','Large star-shaped fortress.',imgs.alba],['City','Sighișoara','Medieval Citadel','Clock Tower and cobbled lanes.',imgs.sighisoara],['City','Brașov','Old town & Tâmpa','Council Square and city viewpoint.',imgs.brasov],['Sight','Bran','Bran Castle','Go early to avoid August crowds.',imgs.bran],['View','Transfăgărășan','Bâlea Lake','The defining alpine stop.',imgs.balea],['View','Transfăgărășan','Vidraru Dam','Strong stop on the southern descent.',imgs.transalpina],['Food','Rânca','TARA / Alessia','Mountain comfort food.',imgs.ranca],['Food','Sibiu','Kombinat','Modern dinner option.',imgs.sibiu],['Food','Alba Iulia','PUB13','Dining inside the citadel.',imgs.alba],['Food','Brașov','Le Petit Bistro','Old-town meal stop.',imgs.brasov],['Food','Cârțișoara','Curly-Burly','Relaxed gastropub.',imgs.ranca]];
const checks=['Thermal layer and rain shell','Helmet, gloves, boots and armour','BMW R 1250 GS controls and riding modes checked','Tyres, fluids, lights and luggage straps','Offline maps and hotel addresses','Phone mount, charging cable and power bank','Romanian lei, documents, water and snacks'];
const wmo=c=>({0:['☀️','Clear'],1:['🌤️','Mostly clear'],2:['⛅','Partly cloudy'],3:['☁️','Overcast'],45:['🌫️','Fog'],61:['🌦️','Light rain'],63:['🌧️','Rain'],65:['🌧️','Heavy rain'],80:['🌦️','Showers'],81:['🌧️','Showers'],82:['⛈️','Heavy showers'],95:['⛈️','Thunderstorm']}[c]||['🌦️','Variable']);
const weather={};
async function loadWeather(){$('#weatherGrid').innerHTML='<div class="weather">Loading live route weather…</div>';await Promise.all(wxCities.map(async c=>{try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${c[1]}&longitude=${c[2]}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Europe%2FBucharest&forecast_days=16`;let j=await (await fetch(u,{cache:'no-store'})).json(),i=j.daily.time.indexOf(c[3]),q=wmo(j.current.weather_code);weather[c[0]]={icon:q[0],desc:q[1],now:Math.round(j.current.temperature_2m),feel:Math.round(j.current.apparent_temperature),wind:Math.round(j.current.wind_speed_10m),trip:i>=0?`${Math.round(j.daily.temperature_2m_min[i])}–${Math.round(j.daily.temperature_2m_max[i])}°, rain ${j.daily.precipitation_probability_max[i]}%`:null}}catch(e){weather[c[0]]={err:true}}}));renderWeather();renderDays();$('#weatherStatus').textContent='Updated '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})+' · refreshes whenever the app opens.'}
function renderWeather(){$('#weatherGrid').innerHTML=wxCities.map(c=>{let w=weather[c[0]];return `<article class="weather"><div class="city">${c[0]}</div>${w&&!w.err?`<div class="temp">${w.icon} ${w.now}°</div><div class="cond">${w.desc} · feels ${w.feel}° · wind ${w.wind} km/h</div><div class="meta">${w.trip?'Trip day: '+w.trip:'Trip forecast appears automatically when available'}</div>`:'<div class="cond">Weather unavailable</div>'}</article>`}).join('')}
function wx(city){let w=weather[city];return w&&!w.err?`${w.icon} ${w.now}° now · feels ${w.feel}° · wind ${w.wind} km/h${w.trip?' · trip '+w.trip:''}`:'Live weather loading…'}
function nav(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+id)}
function renderDays(){$('#days').innerHTML=days.map(x=>`<button class="day" data-day="${x.d}"><div class="dayArt" style="background-image:url('${x.img}')"><span class="dayNo">0${x.d}</span></div><div class="dayCopy"><h3>${x.r}</h3><p>${x.e}</p><div class="metaRow"><span>🏍 ${x.km}</span><span>◷ ${x.t}</span></div><div class="status">${wx(x.city)}</div></div></button>`).join('');$$('[data-day]').forEach(b=>b.onclick=()=>showDay(+b.dataset.day))}
function showDay(n){let x=days.find(v=>v.d===n);$('#detailContent').innerHTML=`<div class="detailHero" style="background-image:url('${x.img}')"><div class="detailHeroCopy"><div class="ey" style="color:#dceee6">Day ${x.d}</div><h2>${x.r}</h2><p>${x.km} · ${x.t}</p></div></div><div class="note"><b>Live weather</b><p>${wx(x.city)}</p></div><div class="section"><div class="ey">What to expect</div><h3>${x.e}</h3></div><div class="section"><div class="ey">Stops & photo points</div>${x.st.map(s=>`<article class="stop"><img src="${s[2]}" alt="${s[0]}" loading="lazy"><div class="stopBody"><b>${s[0]}</b><p>${s[1]}</p></div></article>`).join('')}</div><div class="note"><b>🍽 Food</b><p>${x.food}</p></div><div class="note warn"><b>🏍 BMW R 1250 GS rider note</b><p>${x.note}</p></div>`;nav('detail')}
function renderPlaces(f='All'){$('#filters').innerHTML=['All','View','City','Sight','Food'].map(x=>`<button class="filter ${x===f?'active':''}" data-filter="${x}">${x}</button>`).join('');$('#placesList').innerHTML=places.filter(p=>f==='All'||p[0]===f).map(p=>`<article class="place"><img src="${p[4]}" alt="${p[2]}" loading="lazy"><div class="placeBody"><span class="tag">${p[0]}</span><h3>${p[2]}</h3><p><b>${p[1]}</b> · ${p[3]}</p></div></article>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>renderPlaces(b.dataset.filter))}
function renderChecks(){$('#checks').innerHTML=checks.map((x,i)=>`<label class="check"><input type="checkbox" data-c="${i}"><span><b>${x}</b></span></label>`).join('');let s=JSON.parse(localStorage.getItem('motoChecks')||'[]');$$('[data-c]').forEach(c=>{c.checked=s.includes(+c.dataset.c);c.onchange=()=>localStorage.setItem('motoChecks',JSON.stringify($$('[data-c]').filter(x=>x.checked).map(x=>+x.dataset.c)))})}
function makeMap(){let m=L.map('map',{scrollWheelZoom:false}).setView([45.7,24.5],7),ll=[];L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(m);route.forEach((p,i)=>{ll.push([p[1],p[2]]);L.marker([p[1],p[2]]).addTo(m).bindPopup(`<b>${p[0]}</b><br>${p[3]}<br><a target="_blank" href="https://www.openstreetmap.org/?mlat=${p[1]}&mlon=${p[2]}#map=14/${p[1]}/${p[2]}">Open location</a>`)});L.polyline(ll,{color:'#103f35',weight:5,dashArray:'9 8'}).addTo(m);m.fitBounds(ll,{padding:[25,25]})}
$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#back').onclick=()=>nav('itinerary');$('#share').onclick=async()=>{let d={title:'Romania Moto Loop',text:'Our BMW R 1250 GS Romania trip',url:location.href};navigator.share?await navigator.share(d).catch(()=>{}):(await navigator.clipboard.writeText(location.href),alert('Link copied'))};$('#refresh').onclick=loadWeather;renderDays();renderPlaces();renderChecks();makeMap();loadWeather();let h=location.hash.slice(1);if(['overview','itinerary','places','essentials'].includes(h))nav(h);